export const FINISH_LOADING = 'FINISH_LOADING'
export const START_LOADING = 'START_LOADING'

export const OPEN_POPUP = 'OPEN_POPUP'
export const CLOSE_POPUP = 'CLOSE_POPUP'

export const SHOW_TOAST = 'SHOW_TOAST'
export const HIDE_TOAST = 'HIDE_TOAST'

export const REGISTER_TOKEN = 'REGISTER_TOKEN'
export const GET_ALL_TOKEN = 'GET_ALL_TOKEN'

export const GET_VALIDATORS = 'GET_VALIDATORS'

export const SHOW_OVERLAY = 'SHOW_OVERLAY'
export const HIDE_OVERLAY = 'HIDE_OVERLAY'
export const TOGGLE_OVERLAY = 'TOGGLE_OVERLAY'
